name: Release

on:
  push:
    branches: ['release/**']
    
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: dump version
        run: cat VERSION
